#!/bin/bash
# Need to make excutable chmod +x softLinks
src=$(pwd)
tgt1="/usr/lib/freecad"
tgt2="/usr/lib/freecad-daily"
sudo rm -r $tgt1/Mod/GDML
sudo ln -s $src/Mod $tgt1/Mod/GDML
sudo rm -r $tgt2/Mod/GDML
sudo ln -s $src/Mod $tgt2/Mod/GDML
